### PR TITLE
Hide video views homepage - v1.6

### PR DESCRIPTION
**Pull request by Perseus333**
Hides views from homepage.

Same as #36 but rebased to v1.6

### CODE REVIEW

**Review by Pedro-Gregorio — APPROVED** [review]
Ready to merge :)

**Comment by Pedro-Gregorio** [comment]
@Perseus333 
Can you confirm this doesn't make views hide sometimes on the subscriptions page or on the channel page?
Here's what I did: access youtube home page -> subscriptions -> home page -> back to subscriptions and the views were hidden.

**Comment by Perseus333** [comment]
Sure! Tomorrow I'll check.

**Comment by Pedro-Gregorio** [comment]
Appreciate that! The issue occurs for both the views and that posted x time ago.

**Comment by Pedro-Gregorio** [comment]
@Perseus333 please ignore this! I've fixed the issue, and had nothing to do with your feature :)

**Comment by Perseus333** [comment]
> @Perseus333 Can you confirm this doesn't make views hide sometimes on the subscriptions page or on the channel page? Here's what I did: access youtube home page -> subscriptions -> home page -> back to subscriptions and the views were hidden.

You are right! What??! I know that this is because of the generic selector (which I will fix) but this shouldn't happen anyways. Due to the attribute(?): `pageTypes: [PAGE_TYPES.HOME],` it should only apply to the homepage and not the subscriptions. Maybe there is an issue with the handling of that?

(1 hour later)

I have found that the issue probably lies in that the eventListener `yt-navigate-finish` doesn't trigger when you go back to a cached(?) page. So this is most likely the source of the issue. I have tried several others like:
- yt-navigate-cache
- track
- transitioned
- load

And every single time nothing changes. @Pedro-Gregorio, if you know what could be the source of the issue tell me because right now I'm lost.

**Comment by Pedro-Gregorio** [comment]
Hey there, @Perseus333 !
I've researched a bit for yesterday, but couldn't really figure out why that was happening - code wise; Page wise, it's due to the fact none of the events (load and navigate) are triggered on the scenario I've mentioned.
It's so wierd, because there are things from the home page (tabs, if I'm not mistaken) which used to mess up things on the subscriptions, until the page validation was implemented - which can be improved btw, I'm working on that. I really don't know what's going on.
I've also noticed a slight performance decrease with those 2 elements being hidden (views and time), but, again, I can't really conclude on why.
Anyways, thank you for confirming the error and don't worry about it for now, as I'll be working on trying to improve content.js and fix the issue :)

**Comment by Perseus333** [comment]
Great! I'll also continue researching to see if I can help you find the issue.

**Pull request merged**
