### PR TITLE
Hides "New" Badge in thumbnails

### PR DESCRIPTION
**Pull request by Perseus333**
Hides the new annoying "New" text that appears on new videos in the homepage.

Btw, sorry for pull-request-bombing but this extension is just too good, I can't stop, I need help. :)

### CODE REVIEW

**Comment by Pedro-Gregorio** [comment]
Hey @Perseus333 ! Thank you for your contributions, you were on a roll yesterday!!
Can you please provide a screenshot of what the "new" badge is? I think I've never seen it.
Everything else looks ok, I just need to understand what we're targetting here :)

**Comment by Perseus333** [comment]
Thanks! I really enjoy this project, it is so cool! :D

Here you can see a screenshot of the "new" badge:

Sometimes, YouTube recommends a lot of new videos and it can get pretty annoying.

image

**Comment by Pedro-Gregorio** [comment]
Hey again, @Perseus333 , isn't that label created by an extension? 🤔

**Comment by Perseus333** [comment]
No, it isn't. If you don't use an account to view YouTube then it doesn't appear.

I have seen it for a long time in my tablet device in the footer of the thumbnail and now it appeared on the browser version of YouTube. Also, I don't have any extensions that alter YouTube enabled in either Chromium or Firefox.

Although it could be a beta feature and this is just something about my geolocation?

**Comment by Pedro-Gregorio** [comment]
Hey @Perseus333 ! Sorry about this, but I deleted the 1.5.0 branch after merging it to master, ahead of the release. Could you please add this to the newly created 1.6.0?

**Pull request closed without merging**
